### ISSUE TITLE
Assignment and canonisation

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln-docs#20]
Prediciton -> atom number assignment

Numérotation par rapport à un molfile canonique

1H -> load molfile -> add missing H -> add missing stereochemistry

![image](https://user-images.githubusercontent.com/1484241/127107971-9bd01013-e38d-48b8-8d16-32548e49850a.png)

Algorithme: HOSE code based on nmrshiftdb.

The Hierarchically Ordered Spherical description of Environment (HOSE) code method describe the chemical environment of the atom by layers like onion peels 

![image](https://user-images.githubusercontent.com/1484241/127109639-0e74fe64-ea10-4434-b72b-6810cc53fbed.png)

![image](https://user-images.githubusercontent.com/1484241/127109825-1853a12f-8dc7-4ea3-a6ce-0bfdf0eb9a3c.png)

![image](https://user-images.githubusercontent.com/1484241/127109918-11b3ee7c-93e3-4f59-a99c-bf87834a2c69.png)

**Comment by louisefoltzerdecian** [comment]
Fixed
