### ISSUE TITLE
Use 'includes' and summary

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln-docs#70]
Currently in the page:

https://docs.c6h6.org/docs/eln/uuid/187642421e225f8cfcd65a9243394a72

We have links to another pages rather than a summary that expands. 

@remisch could you fix this ?

**Comment by remisch** [comment]
I found equations given as : `<img src="https://tex.cheminfo.org/?tex=Roundness%20%3D%20%5Cfrac%7B4%20*%20ROI_%7Bsurface%7D%7D%7B%5Cpi%20*%20Feret_%7Bmax%7D%7D"/> `
Would it be better to write LaTeX equations directly in the md file, so we don't see the white background? @lpatiny 
<img width="898" alt="Screenshot 2022-10-04 at 17 38 12" src="https://user-images.githubusercontent.com/89319217/193863626-58eb8268-a297-4f97-9e2f-ac86586f440d.png">
